# Generated by Django 5.2.16 on 2026-07-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desconexiones', '0011_catalogacion_fabricantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParaleloCeldaPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subestacion_a', models.CharField(db_index=True, max_length=120)),
                ('celda_a_fid', models.BigIntegerField()),
                ('celda_a_codigo', models.CharField(max_length=120)),
                ('subestacion_b', models.CharField(db_index=True, max_length=120)),
                ('celda_b_fid', models.BigIntegerField()),
                ('celda_b_codigo', models.CharField(max_length=120)),
                ('nivel_kv', models.FloatField(default=13.8)),
                ('observacion', models.CharField(blank=True, max_length=300)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['subestacion_a', 'celda_a_codigo', 'subestacion_b', 'celda_b_codigo'],
                'constraints': [models.UniqueConstraint(fields=('celda_a_fid', 'celda_b_fid'), name='paralelo_celdas_unico')],
            },
        ),
    ]
