# Generated by Django 5.2.16 on 2026-07-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desconexiones', '0012_paraleloceldapermitido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionManiobras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corriente_max_apertura_aisladero_a', models.DecimalField(decimal_places=2, default=12, max_digits=8)),
                ('corriente_max_cierre_aisladero_a', models.DecimalField(decimal_places=2, default=12, max_digits=8)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
