# Generated by Django 5.2.16 on 2026-07-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desconexiones', '0013_configuracionmaniobras'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmaniobras',
            name='maniobra_fin_desenergizacion',
            field=models.TextField(default='Verificar las 5 reglas de oro para trabajo eléctrico seguro y realizar la entrega de campo'),
        ),
        migrations.AddField(
            model_name='configuracionmaniobras',
            name='maniobra_fin_energizacion',
            field=models.TextField(default='Informar a centro de control la terminación y normalización de los trabajos'),
        ),
        migrations.AddField(
            model_name='configuracionmaniobras',
            name='maniobra_inicio_desenergizacion',
            field=models.TextField(default='Solicitar a centro de control la apertura del permiso operativo y el inicio de maniobras'),
        ),
        migrations.AddField(
            model_name='configuracionmaniobras',
            name='maniobra_inicio_energizacion',
            field=models.TextField(default='Solicitar a centro de control la apertura del permiso operativo y el inicio de maniobras de energización'),
        ),
    ]
