# Generated by Django 5.2.16 on 2026-07-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desconexiones', '0014_configuracionmaniobras_maniobra_fin_desenergizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmaniobras',
            name='usuarios_totales_cens',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
