# Generated by Django 5.2.16 on 2026-07-30 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desconexiones', '0015_configuracionmaniobras_usuarios_totales_cens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AprendizajeProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(max_length=64, unique=True)),
                ('tipo_cambio', models.CharField(max_length=20)),
                ('motivo', models.TextField()),
                ('protocolo', models.JSONField(default=list)),
                ('contexto', models.JSONField(default=dict)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
